### ISSUE TITLE
Add a "60-second Indexer" to the mdbook

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#101]
- [Reference comment](https://fuellabs.slack.com/archives/C02RU9MNVKN/p1657059970763019)
- Challenge: Create an indexer, in a project, that can get started indexing in a short amount of time

Additional context
- This wouldn't be so much an in-depth exploration of an indexer as it would be a display of just how quickly you can start a functional indexer service
- Would constitute going from nothing (no repos, no tools, etc) to a fully functioning project
  - This would closely resemble [the Getting Started section in the book](https://fuellabs.github.io/fuel-indexer/master/getting-started/index.html)
- Would possibly require some type of project init command `forc new helloworld --full-project` 
  - Would need some type of command/script to create the project layout
    - Command would bootstrap a Fuel project according to [the documented project layout](https://fuellabs.github.io/fuel-indexer/master/getting-started/fuel-indexer-project.html)
- Could then `echo` some text into the Forc contract, build it, get the JSON ABI, add it to the indexer manifest, deploy the contract
  - Again, this would be some type of bash one-liner 
- Would need some way of interacting with the contract so that a transaction could be triggered

**Comment by SilentCicero** [comment]
Interesting idea. 

I think having a nice starting template is good. Potentially something simple like maybe a Counter contract with a logged structure (so that you can do changing events).

I think you could just have a Rust script which generates the volumes of tx's over time.

The build and config process to use the indexer should be extremely simple, it's should require little to no config and just the schema files and the indexer code, in addition to the smart-contract and maybe some tests.

Need to think on this idea some more, but from a dev-ex perspective, I like the thought.

**Comment by ra0x3** [comment]
Closing as not doing (there are other examples to be had that will display this same functionality)
