### ISSUE TITLE
How to handle case where two different `TypeDefinition`s derive the same `ID`?

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1093]
- We have an `ID` derivation process when using `Entity::new()` that automagically derives the `id` field for `Entity` by hashing all of `Entity`'s fields
- This works fine 99.9% of the time
- However, in small set of cases, two different `Entity`s will derive the same `id` field
  - More on this over in https://github.com/FuelLabs/fuel-indexer/issues/1083
- For now, as a temp workaround, we just bump the executor's cursor and keep indexing data
- Ideally we need to be indexing _all_ data, no skipping anything

**Comment by deekerno** [comment]
I'm going to take this and get it done this week.

_Just to restate the underlying issue_:
Currently, each data record requires a primary key ID of type `u64` . As stated, we have a derivation process for these IDs that automatically derives this ID by computing an SHA-256 hash and taking the first eight bytes and converting that to a `u64`. Clearly, truncating 256 bits into just 64 bits can eventually lead collisions in the primary key as we lose the granularity afforded by the remainder of the bits. Thus, we need a way to generate an identifying value that doesn't lead to collisions. However, no matter what method we choose, we need to ensure that it's idempotent as users can use these IDs to refer to past entities, if desired.

Here are my thoughts:
- Due to `wasm32-unknown-unknown`'s prohibition on input sources, we can't use anything that requires I/O, i.e. timestamps, randomness, etc.
- However, it seems that we could use [UUIDv5](https://datatracker.ietf.org/doc/html/rfc4122#section-4.3) as a unique identifier inside namespaces.
-- I don't think that we can remove the `u64` ID requirement from the indexer service just yet, but perhaps we can add a `uuidv5` string to entities going forward and ensure that we save/load using both values?

@ra0x3, @lostman: Thoughts?

**Comment by ra0x3** [comment]
@lostman @deekerno Do either of you have any reservations about just bumping the `ID` to 128 bits (or something similar) ?
