### ISSUE TITLE
Figure out why indexers are dying implicitly

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1111]
- We have an issue where an indexer will just die, no errors, no warnings, nothing - it just stops
- I created https://github.com/FuelLabs/fuel-indexer/issues/1100 as a temporary fix for this until we can get the time to see what's actually happening under the hood here
- Repro steps:
  - Just deploy a default indexer to the playground, then look at [the Grafana dashboard](https://graphana-beta-1.fuel.network/d/oMe0biyVk/fuel-indexer-playground?orgId=1) 
  - You will see that indexers run for about an hour before they just stop
- It was suggested that we use [tokio-console](https://github.com/tokio-rs/console) to help debug the issue 

Additional context
- High priority on this cause obviously, even with https://github.com/FuelLabs/fuel-indexer/issues/1100 we need to find the root of the issue here and fix it ASAP
- https://github.com/FuelLabs/fuel-indexer/issues/1100 also contains more notes and details/links

**Comment by ra0x3** [comment]
@deekerno Could you paste anything you found on this?

**Comment by deekerno** [comment]
Here are some links that may be helpful to read:
- https://ryhl.io/blog/async-what-is-blocking/ - written by one of the Tokio devs
- https://users.rust-lang.org/t/tokio-from-async-to-sync-and-back-to-async-block-on-vs-spawn-blocking/83438 - same Tokio dev responds to some questions

Some thoughts:
- [`tokio-console`](https://github.com/tokio-rs/console) would be pretty helpful here, even if only to verify that the freeze is due to a task that infinitely blocking. Note that the implementer will have to add `console-subscriber` to the dependencies but also disable the use of `tracing-subscriber` in the codebase, as I found out the hard way that you cannot have use both at the same time. This would only be done to use the tool and not be a permanent change, but it is a bit of a pain to do.
- One can use something like [`lockbud`](https://github.com/BurtonQin/lockbud/tree/all/Code) to see if it can detect any locking bugs due to the use of the `async_std::sync::Mutex`; however, it only supports `std::sync::Mutex` and other similar primitives and one would have to downgrade their Rust version to a older nightly to be able to use it.
- After looking through the code for the `Executor` trait, I wonder if we even need to use `spawn_blocking(...)` at all. Presumably, it's ultimately because of calls to `ff_put_object` and `ff_get_object` in the `Entity` trait which use a blocking call to place data in the database.
-- An idea that I had while waiting to fall asleep: What if we use an [multi-producer single-consumer (MPSC) channel](https://docs.rs/tokio/latest/tokio/sync/mpsc/index.html) to manage interaction with the database? Other than the memory store, it's the only thing that has an `Arc<Mutex> around it (and as far as I can tell, this problem was happening prior to the addition of mutual exclusion around `Store`). The service would create and hold the `Receiver` and then each executor would be created with a `Sender` When things need to be loaded or stored in the database, a message would be sent to the receiver, where it would then be parsed and operated upon accordingly. That _should_ eliminate the need for `spawn_blocking` as we've removed the need for locking and blocking in the executor and the use of `Store` _should_ be safe for concurrent access (if the `wasmer` docs are to be believed).

**Comment by ra0x3** [comment]
@deekerno @lostman 
- Interestingly enough, I see @AlicanC's indexer is still up and running ([Grafana link](https://graphana-beta-1.fuel.network/d/oMe0biyVk/fuel-indexer-playground?orgId=1))
  - Longer than the default indexers I deployed
  - Might offer another clue 
  - If @AlicanC's indexer is based on contract calls, and the default indexer is just saving blocks/transactions - I'm wondering if the load between the two (high load for default indexer, lower load for shoutbox) might be a blue 🤔

**Comment by ra0x3** [comment]
Will wait to confirm on v0.18.4 but fingers crossed https://github.com/FuelLabs/fuel-indexer/pull/1116 was the solution here 🤞🏽

**Comment by ra0x3** [comment]
- I think we can close this as complete. 
- [Indexers seem to be running consistently on the playground now](http://localhost:3000/goto/_dDttsC4R?orgId=1)
- Thanks @deekerno 🏅
