### ISSUE TITLE
Revamp our testing suite and CI

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#1226]
### Overview
This is more so a discussion/tracking issue. We can create smaller/actionable issues from this.

- There's 2 ideas here
  1. Revamp our testing suite
  2. Include this re-vamped testing suite on an efficient CI pipeline 
  

 ### Context
- We've caught a few gnarly bugs in releases lately
  - Even prior to this, we've shipped crazy bugs that broke the service in our QA environment (the playground)
- The cost of releasing bugs is high
  - Patch releases can run long into the day
  - Figuring out the root cause of the issue can take even longer
  - Sometimes these bugs cause us to bug (no pun intended) the devops team -- using even more resources
- Ideally we need tests that can these types of issues before they happen
- We have a decent suite of unit tests 
  - They need to be trimmed down https://github.com/FuelLabs/fuel-indexer/issues/1194
- However, unit tests won't catch issues like https://github.com/FuelLabs/fuel-indexer/issues/1218
- We need to extend our testing
  - Less redundancy in unit tests, so we can shrink the overall footprint of the tests, thus allowing us to add more tests
  - Different types of tests
    - So far we're just using
      - Unit tests 
        - These include e2e tests, and all other tests marked `#[test]`
      - And 1 or 2 integration tests
        - https://github.com/FuelLabs/fuel-indexer/blob/develop/ci/build-and-deploy-examples.bash
        - **We need integration tests for all plugin commands**
    - Ideally we need a set of longer running, analytical "QA" type of tests
      - These tests should spin up and index from various starting points and analyze the output
        - The output would be various performance stats (e.g., memory usage) and indexed data
        - We would write scripts to assert that the stats recorded are within some bounds
        - And if we want to be strict, we'd make this QA success ☝🏽 a pre-requisite for a release 
          - Probably not at the point where we should make QA tests a release _blocker_, but definitely should run them on release or on merge to master

### Progress
I will add more sub-issues here as they're created
- [x] https://github.com/FuelLabs/fuel-indexer/pull/1224
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1194
- [ ] https://github.com/FuelLabs/fuel-indexer/issues/1193
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1229
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1230
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1336
- [x] https://github.com/FuelLabs/fuel-indexer/issues/692
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1036
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1216
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1243
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1252
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1256
- [x] https://github.com/FuelLabs/fuel-indexer/issues/1257

**Comment by deekerno** [comment]
I have some thoughts for adjustments to general development PRs; generally, the CI workflow for a development PR would be as follows:

_First group_
- set-env-vars
- docs-tests
- Cargo.toml check
- `cargo fmt --check` on the workspace
- `cargo clippy --locked --no-default-features` on the workspace
- `cargo clippy --locked --all-targets --all-features` on the workspace

_Second group_
- Unit tests
- E2E and integration tests
-- This would include the optimized tests from #1194 and any new tests added as part of #1230.
- Build default indexer
- Build and test examples

This would speed up development PRs considerably.

Reasoning:
- [`cargo clippy` runs `cargo check`](https://github.com/rust-lang/rust-clippy/blob/c154754b74577906c5d55d57f7daeff02d6a33e7/src/main.rs#L59), which is [`cargo build` without the actual code generation process](https://doc.rust-lang.org/cargo/commands/cargo-check.html#description). I don't think we've had an error that was build-time only in a very, very long time (please correct me if I'm wrong).
-- If we're skittish about not having a build job that actually catches errors in code generation, I think we can move them to the version bump PR type as we would still be able to catch any failed builds before the publishing step.
- The E2E and integration tests generally have to compile the project in order to properly test things from end-to-end so we should be able to catch any failed builds at this step.

@ra0x3, @lostman: Thoughts?

**Comment by ra0x3** [comment]
Closing this out though 1 issue remains (it's a spike) :)
