### ISSUE TITLE
Script and Mint transactions are replaced to empty Script transactions

### ISSUE THREAD

**Issue by a-filippo** [FuelLabs/fuel-indexer#1357]
# Issue

### Description
file: packages/fuel-indexer/src/executor.rs, `fn retrieve_blocks_from_node`
https://github.com/FuelLabs/fuel-indexer/blob/1b345b069e99e846278bcbdcfda23fbe689839ab/packages/fuel-indexer/src/executor.rs#L425

`Script` and `Mint` transactions are replaced to `Transaction::default()`. By this reason inside my indexer these types of transactions are broken. I checked the commit history and file changes, and decided that this problem did not exist before.
Anyway I have a branch which is the expected behavior in my opinion: https://github.com/FuelLabs/fuel-indexer/compare/develop...a-filippo:fuel-indexer:added-script-mint?expand=1

I am attaching an example of log, which shows that both block transactions has `Script` type with empty information.

![2023-09-18 01 07 49](https://github.com/FuelLabs/fuel-indexer/assets/22962790/1bf0dd45-60ff-48f2-bb6d-3679ce67e2b5)

### Versions

- `fuel-indexer`: 0.20.7
- `forc-index`: 0.20.7

**Comment by ra0x3** [comment]
- Doh! Thanks @a-filippo it appears we didn't go back to add some of these cc @deekerno 
- We'll try to get your commit in, so that you can get contribution
- Another note @a-filippo, you'll have to sign something if you want to get your commit into the repo 😅 (standard operating procedure)
  - No rush here, but if not done in a few hours, we'll probably just commit your example ourselves so as to unblock you ASAP :)
