### ISSUE TITLE
Integrate some features from `fuel-core` that should live in `fuel-indexer`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel-indexer#19]
@Voxelot you mentioned there are some features currently integrated in [`fuel-core`](https://github.com/FuelLabs/fuel-core) that might be better suited to `fuel-indexer`. Would you mind listing what you have in mind here?

If some of these features are currently required to get certain downstream tools working, could you also add what those are?

It might be a good idea to prioritise tackling these items so that we can start integrating `fuel-indexer` into the ecosystem so that we can drive forward it's progress with the rest of the tooling. Currently it seems to be falling out of sync, but it does sound like this also has a lot to do with the `#[no_std]` blockers which I'll open an issue for now.

**Comment by Voxelot** [comment]
The main concern I have with making fuel-indexer a hard dependency for base tooling and functionality in fuel are the extensive and heavy dependencies it requires. While fuel-core already feels a bit heavy due to rocksdb, the indexer adds a lot of extra weight with dependencies on things like wasmer/llvm (which has been somewhat alleviated by cranelift support) and reliance on a SQL backend installation like postgres. Adding sqlite support will help alleviate some of the burden, but will still require system-level dependencies to build and run. 

A good starting point for baseline functionality within the indexer would be the block explorer. While fuel-core can easily and efficiently show things like block and transaction history, there's a lot more the block explorer could do when powered by an indexer. Some ideas would be things like:

- Contract to contract interactions
  - For example in etherscan they show ["contract internal transactions"](https://etherscan.io/txsInternal)
- Recent contract events
  - [uniswap example](https://etherscan.io/address/0xc36442b4a4522e871399cd717abdd847ab11fe88#events)
- Contract Analytics
  - [transaction timeseries](https://etherscan.io/address-analytics?m=normal&a=0xc36442b4a4522e871399cd717abdd847ab11fe88&lg=en&cc=USD#tx)

The next big area of functionality would be to augment our swayswap app with functionality similar to what thegraph provides to sushiswap: https://thegraph.com/explorer/subgraph?id=D7azkFFPFT5H8i32ApXLr34UQyBfxDAfKoCEK4M832M6&view=Playground

**Comment by ra0x3** [comment]
- Closing this (as the project has changed quite a bit since this was opened). 
- Feel free to open a new issue if there is something here we should be keeping an eye on :)
