### ISSUE TITLE
Add `revert` command to `forc index`

### ISSUE THREAD

**Issue by deekerno** [FuelLabs/fuel-indexer#464]
In the event that a new asset deployment breaks a previously working index, there should be a way to quickly revert back to the previous version of the index so that indexing is interrupted as little as possible. This would need a new command to be added to `forc index` as well as a new endpoint in the API server.

**Comment by rvmelkonian** [comment]
@deekerno @ra0x3 

As contracts in sway are not currently upgradable, why would an index have multiple versions? Is the case that for the same contract deployed `x`, there could be multiple different indexes `y` and `z`? First index y was deployed, then the developers realised they wanted to index more receipts from that contract so they deploy a new index `z`?

This would mean a new .graphql, .wasm, .yaml file (but same contract_id) value. 

The yaml would contain the same namespace but a new identifier. For eg. 

first index yaml:
   namespace : fuel-defi
   identifier: y
   contract_id: 1234
   
second index yaml:
   namespace: fuel-defi
   identifier: x
   contract_id: 1234
   
The plugin command here could revert `fuel-defi.x` to `fuel-defi.y`. But that would only work in this case. So my question is, how do we want to enforce versioning on the indexes? Maybe I am missing some already existing functionality, but it seems we need it in order to revert to the correct index. 

If we need it I would add a new field on the yaml `version`. I think simple unary numbering would work best, semver probably overkill for indexes.

**Comment by deekerno** [comment]
When I created the issue, the general thought was that a user may need to quickly revert to an old working version of an index instead of having to undo the changes to their WASM code and then attempt to re-deploy the old version; as it stands right now, I don't think the service would start the re-deployed indexer as the blob would already be present in the database and would not kick off the executor creation process due to the hash check in the `asset_already_exists` query. So the plugin command could just get the blob for the immediate prior version and kick off an executor for the index. `IndexerService` should already handle the event in which asset types are the same (check `register_index_from_manifest` in `fuel-indexer/service.rs`), so I don't think it would need new assets across the board. Thoughts?

**Comment by rvmelkonian** [comment]
So just use the last thing already in the DB, that works. maybe the plugin should take an arg namespace + identifier. Then the command would revert to the last instance of that.

**Comment by ra0x3** [comment]
@rvmelkonian 
- Just an FYI our convention so far is to either use the `manifest` at the given `path`, or if no `path` is supplied, to just derive the `manifest` path using the current working directory. [Example](https://github.com/FuelLabs/fuel-indexer/blob/master/plugins/forc-index/src/ops/forc_index_build.rs#L53).

**Comment by rvmelkonian** [comment]
noted thanks, in that case there is no need for the args. Cleaner that way anyway.
