### ISSUE TITLE
Create method to ensure Quickstarts match

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#496]
- We are updating the Quickstart docs in https://github.com/FuelLabs/fuel-indexer/pull/486
- We are also updating the README in https://github.com/FuelLabs/fuel-indexer/issues/490 which will include the same Quickstart as what is mentioned in #486 
- In order to make sure these two things don't get out of sync (they should remain the exact same) we should create some means of keeping the docs/quickstarts in sync

Potential implementation
   - Try to create some type of CI job that will ensure the contents of the Quickstart file, and the Quickstart section of the README are the same
   - Let's discuss other ideas below

**Comment by hrryndrsn** [comment]
Is there a more automated way? eg reference a markdown file in two places?

**Comment by ra0x3** [comment]
@hrryndrsn https://stackoverflow.com/questions/4779582/markdown-and-including-multiple-files

**Comment by hrryndrsn** [comment]
yep or you could just literally string join several 'chapter' markdown files to create a compiled readme. IDK if you can put it in CI because the markdown is it Git right? so maybe you need a readme builder script and the output is committed . then you can diff the changes

**Comment by hrryndrsn** [comment]
ls chapters | xargs | cat file >> readme.md

🤔

**Comment by deekerno** [comment]
This does appear to be possible in mdBook, the program used to build our book. See https://github.com/rust-lang/mdBook/issues/245 which was then fixed by https://github.com/rust-lang/mdBook/pull/372. We could then include certain lines of the README in a way similar to [this](https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file).

**Comment by deekerno** [comment]
I don't think so. The way I envision it working is writing the quickstart once in the README and then including the corresponding lines in the book so that they're in sync that way. The closest I can find to including "markdown in markdown" is this post: https://stackoverflow.com/a/5529508

**Comment by hrryndrsn** [comment]
maybe a more simple approach https://stackoverflow.com/questions/23815120/bash-concatenate-multiple-files-and-add-newline-between-each

just break up the readme into sections in another directory and have a utility script to compile the readme and you can git diff the readme changes and commit that. any changes will be in git.

i think it would be easier to pull content from the book into the readme than the other-way (book --> readme) because the git book cannot reference files outside its out sub scope.

**Comment by hrryndrsn** [comment]
a bash script like this (need testing)
```bash 
README=./README.md
mv README ./README_OLD # save current readme 

# append section files to build new readme 
# you can reuse any md file in the repo 
# change the ordering here easily
docs/1.md >> README
echo >> README
docs/quickstart/index.md >> README
echo >> README
docs/2.md >> README
echo >> README
docs/3.md >> README
echo >> README

# review the changes 
git diff README

# or

diff README ./README_OLD

**Comment by ra0x3** [comment]
@deekerno figured out how to do this [here](https://github.com/FuelLabs/fuel-indexer/blob/master/docs/src/quickstart/index.md). Closing
