### ISSUE TITLE
Move integration tests to a test harness

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#56]
- Tests such as [this](https://github.com/FuelLabs/fuel-indexer/blob/master/indexer/src/database.rs#L214) that test integration between multiple/several components should be used to a test harness file as opposed to in module unit tests

**Comment by mitchmindtree** [comment]
What are the benefits you're foreseeing of moving these into a separate harness?

**Comment by ra0x3** [comment]
@mitchmindtree 
- The thinking here is that [test harness's](https://stackoverflow.com/questions/11625351/what-is-test-harness) are slightly more involved integration tests
- Whereas [unit tests (top paragraph)](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html) test individual components
- [The linked test](https://github.com/FuelLabs/fuel-indexer/blob/master/indexer/src/database.rs#L214) is a generic databse test that uses several components including the wasm, schema, columns, etc
- I'll add the "Low" priority so that this doesn't seem like something urgent
- It's definitely not the end of the world if put integration tests in `#[test]` modules -- just more of a convention thing  
  - I feel like it would be more of a unit test if we used a scaffold to generate all the components required by the test, then broke `load_schema`, `put_object`, and `get_object` into their own test blocks

**Comment by mitchmindtree** [comment]
Yeah totally, I see where you're coming from, and we do set a precedent for it in Sway too.

I guess technically the main difference between it being under a `#[test]` and not, is that under a `#[test]` it gets run as a part of the `cargo test` suite, whereas otherwise it needs to be run from an independent binary.

The latter sounds like the right approach if we need the flexibility to pass in different flags or inputs for the test, or if we are doing something side-effectful like spinning up a stateful DB in the user directory somewhere.

If it's all happening in memory (or even `/tmp`) without any custom inputs, maybe we can get away with having it under a `#[test]` for now? It's quite convenient having it appear along with the rest of the `cargo test` output, particularly as `cargo test` also supports quite a bit of customisation out of the box (like filtering tests, specifying thread counts, etc).

Another option might be to move the more extensive tests into a `test/` directory in the top-level of the associated crate?

**Comment by ra0x3** [comment]
Closing this as complete
