### ISSUE TITLE
Add constraints to indexer services for playground

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#734]
- We've got buy-in from @SilentCicero regarding https://github.com/FuelLabs/fuel-deployment/issues/106
- However before opening something like this up to the public it will require a few constraints to be added to indexer services
- Mainly want to ensure that:
  - Indexers don't run forever. 
    - They should run for enough time to "demo" functionality, then they should stop
    - We could either keep them alive for a certain amount of time/blocks
  - Users that deploy indexers to the playground use authentication
    - This authentication functionality already exists as of v0.6
    - This might require some additional documentation on our JWT usage
      - Maybe a GIF screen-recording might be helpful to show the 5 commands involved?
- I imagine we'd start the service with some flag (e.g., `--playground` or whatever) which will let the service know how/when to remove indexers -- this part is open-ended

CC @deekerno and @rvmelkonian for thoughts

This is something that we would work on as soon as we iron out these last ☝🏽 details

**Comment by rvmelkonian** [comment]
• Assuming the indexer be indexing events from `beta-3`?
• Do we want all of our examples to be deployed to this playground indexer?
• Apart from uptime costs, why don't we want the playground indexer to run forever? Answer to this question will help me understand best way to implement some kind of programmable downtime. 
• If we have our examples deployed to the playground indexer, we will need to write some script or rust code that will execute a bunch of transactions so that queries pull some data from the `beta-3` chain.

**Comment by ra0x3** [comment]
@rvmelkonian
- Yep this playground would be in lock-step with Fuel core (so beta-3 for now)
- No we wouldn't deploy any examples
  - I mean we'd be free to use the service like anyone else is, but we wouldn't specifically need to run any examples on this deployment
- We don't want indexers to run forever because it's just a playground/demo service - not meant for production
- See the first bullet point
