### ISSUE TITLE
Bump fuels sdk to `0.40.0`

### ISSUE THREAD

**Issue by rvmelkonian** [FuelLabs/fuel-indexer#757]
Version 0.40.0 of the SDK is released. Check out the [release notes](https://github.com/FuelLabs/fuels-rs/releases/tag/v0.40.0). 
• Bump the versions in our toml files. 
• Update any tests and or production code if any breaking changes. 

- This should unblock #754 and #748 🥳. Thanks @segfault-magnet for the fast fix on the Parameterize / Tokenizable wasm issue.

**Comment by ra0x3** [comment]
@rvmelkonian Just FYI 
- This is OK cause your work needs a hotfix that's available in 0.40
- But in general when we upgrade, we want to make sure we upgrade _everything_...everywhere...all at once (😆 )
  - But no we wanna make sure we upgrade the entire fuel(s) ecosystem to make sure we have the latest things so we don't have one thing up-to-date (e.g., fuels from the SDK) and other things that are old (e.g., fuel-types, fuel-crypto, etc)
  - Again, totally fine to make an exception here and just do `fuels` since you need a hotfix

CC @deekerno
