### ISSUE TITLE
Support `[Type]` in GraphQL schema

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuel-indexer#888]
- (This description is a little scattered, still working on it)
- We should update our GraphQL codegen functionality to support  list types `[Type]`
- This applies in 2 places, GraphQL _queries_, and GraphQL codegen
- We currently support storing types in an array using `Vec<u8>` via `Blob` types - which translates to a Postgres `bytea`
  - This works fine, but users have to manually serialize/deserialize their types
  - We should automagically do this for users when storing in the DB or fetching from the DB
- Really implementing this would require us to give users some way to mark a GraphQL type as "don't use this for table creation"
  - As of now, every `type` defined in GraphQL schema gets used for table creation
  - But users want to create a `type` and only use it in another `type` (not necessarily have a table created from it)
- [`serde_postgres`](https://docs.rs/serde_postgres/latest/serde_postgres/) might help here

Schema example
```graphql

@no_index  # mark the type as something to not use when creating DB tables
type Basic {
  count: UInt8!
}

type MyEntity {
   id: ID!
   scalars: [UInt8]!  # should support scalars as well
   basics: [Basic]
}
```

Generated struct example
```rust 
struct Basic {
  count: u64,
}

struct MyEntity {
  id: u64,
  scalars: Vec<u64>,
  basics: Option<Vec<Basic>>,
}
```

Example use in indexer

```rust
fn my_indexer_handler(block: BlockData) {
   let basics = (0..2).iter().map(|i| Basic{ count: i }).collect::<Vec<Basic>>();
   let e = MyEntity{ id: 1, basics, scalars: vec![1, 2, 3]  };
   e.save();  // should serialized `MyEntity.basics` and MyEntity.scalars into a Vec<u8>

  let e = MyEntity::load(1).unwrap(); // should deserialize MyEntity.basics into Vec<Basics> and MyEntity.scalars into Vec<u64>
  assert_eq!(e.basics.is_some());

  let basics = e.basics.unwrap();
  assert_eq!(basics.length, 3);
  assert_eq!(basics[0].count, 1);

  assert_eq!(e.scalars, vec![1, 2, 3]);
}
```

**Comment by ra0x3** [comment]
CC @deekerno for thoughts

**Comment by deekerno** [comment]
At first glance, I'm not sure why this would require us to implement a way to not create a table; wouldn't the creation of a more complex type necessitate the creation of a table so that a value is held for each field? If the type of a list field is a simple string or integer, I could see the case for a simple array being stored for the value as Postgres allows for that; however, my immediate thought with that is that it could possibly violate first normal form (1NF) or at least lead to a lot of redundant data being stored.

As I think about it more, we could probably do this by creating relationship tables in which we track the IDs of both the outer struct type and the IDs of elements that would make up the list in the inner field. To request the elements of the list at runtime as part of a user query, we just select for all rows that match the ID of the outer type and then use the IDs of the elements to get the data from the table for the list type.

**Comment by ra0x3** [comment]
@deekerno 
> my immediate thought with that is that it could possibly violate first normal form (1NF) or at least lead to a lot of redundant data being stored.
- I see your point here.
- Yea, if we're storing multiple copies of `Foo` as a blob, that would lead to a lot more data
- What you're saying is just create one `Foo` and add the foreign keys to the list on `Bar` - that way, lists are just `ID` types
- Agreed here
- My initial concern with that approach is I wasn't sure from a GraphQL _querying_ perspective how that would work - feel free to sort've elaborate on that here, which might make things make more sense for me.


As far as implementation goes (using the example above):
- The user would still have to create and save a `Basic`
- A List of foreign keys `[Basic]` and a list of scalars `[UInt8]` would for the most part be the same? Since foreign keys are just an `ID`
- Another question is how we would resolve these foreign keys into their respective objects
  - When we grab `MyEntity` from the DB, `MyEntity.basics` would just be `Vec<u64>` 
  - Unless.....we actually start using our our `ColumnType::ForeignKey` ([which we currently don't really use](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer-database/database-types/src/lib.rs#L133))
  - Either way, not knowing how much space to allocate when calling [`get_object`](https://github.com/FuelLabs/fuel-indexer/blob/master/packages/fuel-indexer/src/ffi.rs#L117) via the FFI might complicate things (since we'd be needing to call more `get_object`s to resolve the foreign keys).
