### ISSUE TITLE
Inform User about possible missing environment vars

### ISSUE THREAD

**Issue by 0xmovses** [FuelLabs/fuel-indexer#889]
Sometimes a user is presented with this message, even after installing `llvm`.

```
error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
```
If they were to run:
`clang --version`
They might see:
```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Whereas we want it to be:
```
Homebrew clang version 16.0.2
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```
The diff here being the `InstalledDir`, clang does not always link to llvm even after its installed. In this case what the user needs to do is add:
```
export LIBCLANG_PATH="/opt/homebrew/opt/llvm/lib"
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
```
This reminder *has* been added to our docs, but many users may miss this. It would be great if we could do the following:
1. Check whether a user is on an M1 system
2. If so, check for an updated clang binary

NOTE: these are all read operations, we don't want to write anything to the users system.
If the users `InstalledDir` does not point to llvm then we want to link them to our docs that mentions the possible missing vars. 

There could be a better way of presenting this info to them in the terminal, but this is the general gist.

**Comment by ra0x3** [comment]
- +1 here.
- Literally just experienced this with a user a day or two ago
- A really eye-catching nicely-formatted message here would be super helpful
- I might even go as far to say we maybe should read the output of a failed `forc index build` and look for wasm-related output in order to present this message their as well
  - This also happens frequently.
- I'll add some priority on this given how often users stub their toe on this
